name: Transport Scheduler

on:
  schedule:
    - cron: '*/25 * * * *'    # every 15 minutes
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies (server)
        run: npm install

      - name: Install dependencies (scheduler)
        run: npm install
        working-directory: scheduler

      - name: Write service account JSON
        run: |
          # Convert any “\n” escapes back into real newlines:
          printf '%b' "${{ secrets.GOOGLE_SERVICE_JSON }}" \
            > server/utils/auth.json

      - name: Debug auth.json        # ← optional, but very useful
        run: |
          echo '--- START auth.json ---'
          sed -e 's/$/↵/' server/utils/auth.json | head -n 20
          echo '---- END auth.json ----'

      - name: Run transport scheduler
        run: node run-scheduler.js
        env:
          SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
          DEST_SHEET_ID:   ${{ secrets.DEST_SHEET_ID }}

